version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@0.0.13
  datacamp-deploy: datacamp/deploy@0.0.30
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          name: build
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          extra-docker-args: "--build-arg NPM_TOKEN=${NPM_TOKEN}"
      - datacamp-deploy/deploy: # Staging
          context: org-global
          requires:
            - build
          ecs-deploy-url: $STAGING_DEPLOY_URL
          ecs-deploy-password: $STAGING_ECS_DEPLOY_PASSWORD
          filters:
            branches:
              only:
                - master
      - datacamp-ecr/pull_push_to_account:
          context: org-global
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
      - datacamp-deploy/deploy: # Production
          context: org-global
          requires:
            - datacamp-ecr/pull_push_to_account
          ecs-deploy-url: $PROD_DEPLOY_URL
          ecs-deploy-password: $PROD_ECS_DEPLOY_PASSWORD
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/